In [1]:
import numpy as np

In [ ]:
# Example 1 - muliti list array or multi dimensional array

In [8]:
array1 = np.array([[1,2,3,4,],[8,9,10,11]])

In [10]:
array1

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [ ]:
# Example 2 - mulitiplying array

In [9]:
array1*array1

array([[  1,   4,   9,  16],
       [ 64,  81, 100, 121]])

In [ ]:
# Example 4 - subtracting array

In [11]:
array1 - array1

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
# Example 5 - Division  array

In [15]:
1/array1


array([[1.        , 0.5       , 0.33333333, 0.25      ],
       [0.125     , 0.11111111, 0.1       , 0.09090909]])

In [ ]:
# Example 6 -  array with  powers

In [14]:
array1**3

array([[   1,    8,   27,   64],
       [ 512,  729, 1000, 1331]], dtype=int32)