In [2]:
import numpy as np

In [5]:
arr= np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:

# Example 1 -  Creating array with  square root
arr_sqr = np.sqrt(arr)


In [10]:
arr_sqr

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [ ]:
# Example 2 - Finding  Expotential

In [13]:
arr_exp= np.exp(arr)
arr_exp

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [14]:
# Example 3  - Binary Functions
to do thsi  first we  creat two array with some  random numbers

In [18]:
A= np.random.randn(10)

A


array([-2.14798518,  0.4901671 , -0.18219893,  0.65610974,  1.10290391,
        0.35929024,  0.83548313,  0.22766913, -0.43567053,  1.33354373])

In [20]:
B= np.random.randn(10)
B

array([-0.77890248,  0.28762205,  0.08410766,  0.19388654,  0.60137308,
        0.87364386,  1.76501159,  0.0274357 , -1.60368202, -1.67273964])

In [21]:
#Binary Functions
#Addition 
np.add(A,B)

array([-2.92688765,  0.77778915, -0.09809127,  0.84999628,  1.70427699,
        1.2329341 ,  2.60049472,  0.25510483, -2.03935256, -0.33919591])

In [23]:
#minimum
np.minimum(A,B)

array([-2.14798518,  0.28762205, -0.18219893,  0.19388654,  0.60137308,
        0.35929024,  0.83548313,  0.0274357 , -1.60368202, -1.67273964])

In [31]:
# Example 4
website ='https://www.khanacademy.org/math/algebra/x2f8bb11595b61c86:exponential-growth-decay/x2f8bb11595b61c86:exponential-vs-linear-growth/v/exponential-growth-functions'
import webbrowser
webbrowser.open(website)

True