In [1]:
import numpy as np

In [2]:
# Example 1

In [6]:
arr= np.arange(0,11) # we craet a range for value (0 to 10)

In [7]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Example 2 -  for Indexing

In [11]:
arr[6] # with in that range we processing indexing

6

In [12]:
# Example 3 - with in that earlier range we pulling out Particular values  

In [13]:
arr[1:5] # this will show up array from 1 to 4 , 5 wont be part of this array

array([1, 2, 3, 4])

In [14]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [25]:
arr[3:7]

array([100, 100, 100, 100])

In [ ]:
# Example 4- resting array

In [26]:
arr=np.arange(0,11)

In [27]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
# Example 5 - slicing array

In [29]:
slice_of_arr=arr[0:6]# this will slice array from 0 to 10 to 0 to 6

In [30]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
# Example 6  - short cut to select all elements

In [31]:
slice_of_arr[:] = 88

In [32]:
slice_of_arr

array([88, 88, 88, 88, 88, 88])

In [33]:
arr # changing value in slice of array not in my array itself

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [34]:
arr_copy = arr.copy()

In [35]:
arr_copy

array([88, 88, 88, 88, 88, 88,  6,  7,  8,  9, 10])

In [36]:
# Example 7 - Indexing 

In [38]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [40]:
arr_2d[0] # 0 represent  1st row in the above array

array([ 5, 10, 15])

In [41]:
arr_2d[1] # 1 represent  2nd row in the above array

array([20, 25, 30])

In [47]:
arr_2d[1][0] # 1 repesent 2nd row and 0 represent  first  column # Note comma should not come inbetween

20

In [48]:
# Example 8 - chossing particular column and  row in given array

In [61]:
arr_2d[0:2,1:3] 

array([[10, 15],
       [25, 30]])

In [ ]:
# above function [0:2, 1:3] - first comes row next comes column
  0:2 - includes row 0  and 1 and this will not include row 2 
        0(1st row) , 1 ( 2nd row)
  1:3  - Given array have 3 columns 0,1,2  this function includes 2nd and 3 rd column
        1 ( 2nd column) , 2 ( 3rd column)

In [63]:
# above function can also be return as below
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [64]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [67]:
arr_2d[1:,:2] # sample 2

array([[20, 25],
       [35, 40]])

In [71]:
arr_2d[1:, 1:] # sample 3

array([[25, 30],
       [40, 45]])

In [72]:
# Example 9  - Fancy Indexing

In [74]:
arr3d = np.zeros((10,10))

In [75]:
arr3d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [78]:
arr3d_length=arr3d.shape[1]

In [79]:
arr3d_length

10

In [95]:
for i in range(arr3d_length):  # sample 1
 arr3d[i]=3
# for items  in range  arr3d_lenght we  fix all i = 1, this changes all zero to 1
             

In [96]:
arr3d

array([[3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.]])

In [99]:
# sample 2

for i in range (arr3d_length): 
    arr3d[i]=i
# when we assign i = i this will reslt as below  each  colum will represt uniqe value  however  rows looks similar

In [100]:
arr3d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [105]:
# sample 3
#we can choose any one or few  row in given array with  below functoin

arr3d[[8,4,7]]

#by this we can choose one or  few  rows in order as we required

array([[8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])