In [5]:
import numpy as np


In [ ]:
# Example 1 - How to save array

In [4]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [6]:
np.save( 'myarray',arr) # saving  earlier  created arr array with the name "myarray"

In [7]:
arr = np.arange(10) # creating another array with  same  name 'arr'
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.load('myarray.npy') # loading  previous saved array- name of the file with  file  extention

array([0, 1, 2, 3, 4])

In [ ]:
# Example 2  - changing previously saved array with new name 


In [15]:
arr1 = np.load('myarray.npy')
arr1

array([0, 1, 2, 3, 4])

In [16]:
arr2=arr
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
# Example 3  - Saving  both array as Zip file

In [21]:
np.savez('comb.npz',x=arr1,y=arr2) # this will assign a function file named comb buy ziping two file names X and Y

In [23]:
archive_array= np.load('comb.npz') # this will creat a file named archived for previous function

In [24]:
archive_array ['x'] # exporting  each element of  function individually

array([0, 1, 2, 3, 4])

In [25]:
archive_array ['y']

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
#Example  4 -  Lets make a Matrix

In [28]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [30]:
np.savetxt('mytextarray.txt',arr) # save text file

In [31]:
np.loadtxt('mytextarray.txt')# loading  text file

array([[1., 2., 3.],
       [4., 5., 6.]])