In [12]:
import numpy as np
import pandas as pd
from pandas import DataFrame,Series


In [2]:
# Concatenate using Numpy
# we will be working on DataFrame and Matrices

In [5]:
arr1= np.arange(9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [6]:
np.concatenate([arr1,arr1],axis=1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [7]:
np.concatenate([arr1,arr1],axis=0)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [8]:
# concatenate with Pandas

In [13]:
ser1 = Series([0,1,2],index=['T','U','V'])
ser2 = Series ([3,4],index=['X','Y'])
ser1


T    0
U    1
V    2
dtype: int64

In [14]:
ser2

X    3
Y    4
dtype: int64

In [16]:
pd.concat([ser1,ser2])

T    0
U    1
V    2
X    3
Y    4
dtype: int64

In [17]:
pd.concat([ser1,ser2],axis=1)

0    1
T  0.0  NaN
U  1.0  NaN
V  2.0  NaN
X  NaN  3.0
Y  NaN  4.0

In [18]:
# adding markers or keys to concat result

In [19]:
pd.concat([ser1,ser2],keys=['cat1','cat2'])

cat1  T    0
      U    1
      V    2
cat2  X    3
      Y    4
dtype: int64

In [21]:
dframe1= DataFrame(np.random.randn(4,3),columns=['X','Y','Z'])
dframe2 = DataFrame(np.random.randn(3,3),columns=['Y','Q','X'])

In [22]:
dframe1

X         Y         Z
0 -0.589756 -0.564423  1.388173
1 -0.795099 -1.073870  0.257556
2  1.118891 -0.350621  0.345298
3  0.452505 -0.632963  0.565260

In [23]:
dframe2

Y         Q         X
0 -0.017996 -0.213443 -0.267663
1  0.177136  0.229221  1.827369
2 -0.510322 -1.009819 -0.503677

In [25]:
pd.concat([dframe1,dframe2])

X         Y         Z         Q
0 -0.589756 -0.564423  1.388173       NaN
1 -0.795099 -1.073870  0.257556       NaN
2  1.118891 -0.350621  0.345298       NaN
3  0.452505 -0.632963  0.565260       NaN
0 -0.267663 -0.017996       NaN -0.213443
1  1.827369  0.177136       NaN  0.229221
2 -0.503677 -0.510322       NaN -1.009819

In [26]:
# to ignore the Index

In [27]:
pd.concat([dframe1,dframe2],ignore_index=True)

X         Y         Z         Q
0 -0.589756 -0.564423  1.388173       NaN
1 -0.795099 -1.073870  0.257556       NaN
2  1.118891 -0.350621  0.345298       NaN
3  0.452505 -0.632963  0.565260       NaN
4 -0.267663 -0.017996       NaN -0.213443
5  1.827369  0.177136       NaN  0.229221
6 -0.503677 -0.510322       NaN -1.009819