In [ ]:
# Example 1

In [23]:
my_list1 = [1,2,3,4,5] #creating list

In [24]:
my_array1 = np.array(my_list1) # definig function

In [25]:
my_array1 # executing  function

array([1, 2, 3, 4, 5])

In [ ]:
#Example 2

In [ ]:
# combining two list

In [26]:
list_2 =[11,22,33,44,55]  #creating list

In [28]:
list_all =[my_list1,list_2] #creating list

In [29]:
array_2 = np.array(list_all) # definig lsit

In [30]:
array_2  # executing list

array([[ 1,  2,  3,  4,  5],
       [11, 22, 33, 44, 55]])

In [ ]:
# Example 3

In [ ]:
# knowing the shape of the array

In [31]:
array_2.shape

(2, 5)

In [32]:
# Example 4 - Knowing the data type of the array

In [33]:
array_2 .dtype

dtype('int32')

In [34]:
# Example 5 - Special case array in case if we want all Zero in the array

In [58]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [59]:
my_zero_array= np.zeros((3,4))

In [65]:
my_zero_array.dtype

dtype('float64')

In [ ]:
# Example 6 - Special case array in case if we want all one's in the array

In [52]:
np.ones((2,5), dtype= int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [56]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [66]:
np.ones([5,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [67]:
# Example 7 - Special case array in case if we want all empty cell in the array

In [68]:
np.empty(4) # for some reason np.empty

array([6.37401647e-067, 2.16847421e-028, 1.06532414e-312, 0.00000000e+000])

In [ ]:
#Example 8 -  identity Matrix , diagolnal of 1 rest all will be 0

In [64]:
np.eye(5) 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Example 9 - Arrage function

In [70]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [71]:
np.arange(4,20,3) # this function means start at 4 stop at 20  step 3 (difference of 3 each)

array([ 4,  7, 10, 13, 16, 19])